name: lambda-deploy
version: "1.0.0"
trigger: manual
repo: lambda-deploy

jobs:
  - job_type: LAMBDA_DEPLOY
    version: "1.0.0"
    jenkinsfiles:
      launcher: Jenkinsfile.launcher
      watcher: Jenkinsfile.watcher
    parameter_sources:
      function_name: "input:FUNCTION_NAME"
      alias_name: "input:ALIAS_NAME"
      test_payload: "input:TEST_PAYLOAD"
      expected_status_code: "input:EXPECTED_STATUS_CODE"
